name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Change to your region

      - name: Store Secret in AWS SSM
        run: |
          aws ssm put-parameter \
            --name "TWITCH_OAUTH_TOKEN" \
            --value "${{ secrets.TWITCH_OAUTH_TOKEN }}" \
            --type "SecureString" \
            --overwrite

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/praes-bot  # Change to your app directory
            git pull origin main  # Pull latest changes
          
            # Ensure Python & dependencies are installed
            python3 -m venv venv  # Create virtual environment
            source venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements.txt  # Install dependencies
          
            # Load secret from AWS SSM
            export TWITCH_OAUTH_TOKEN=$(aws ssm get-parameter --name "TWITCH_OAUTH_TOKEN" --with-decryption --query "Parameter.Value" --output text)
          
            # Run the Python script
            nohup python3 main.py > output.log 2>&1 &
          EOF
   
