name: Deploy Python Script to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Store Secret in AWS SSM
      run: |
        aws ssm put-parameter \
          --name "TWITCH_OAUTH_TOKEN" \
          --value "${{ secrets.TWITCH_OAUTH_TOKEN }}" \
          --type "SecureString" \
          --overwrite

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Upload SSH private key to GitHub Actions
    - name: Add SSH private key to GitHub Actions
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user
          if [ ! -d "praes-bot" ]; then
            git clone https://github.com/theReuben/praes-bot.git praes-bot
          fi
          cd praes-bot
          git pull origin main
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
        EOF

