name: Deploy Python Script to EC2

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Store Secret in AWS SSM
      run: |
        aws ssm put-parameter \
          --name "TWITCH_OAUTH_TOKEN" \
          --value "${{ secrets.TWITCH_OAUTH_TOKEN }}" \
          --type "SecureString" \
          --overwrite

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure your requirements.txt is in the repo

    # Upload SSH private key to GitHub Actions
    - name: Add SSH private key to GitHub Actions
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Make sure to add your SSH private key in GitHub Secrets

    # Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /path/to/your/project
          git pull origin main  # Pull latest changes (optional, depends on your repo setup)
          python3 your_script.py  # Replace with your script filename
        EOF
