name: Upload Secret to AWS SSM

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  upload-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1  # Change to your AWS region

      - name: Store Secret in AWS SSM
        run: |
          aws ssm put-parameter \
            --name "TWITCH_OATH_TOKEN" \
            --value "${{ secrets.TWITCH_OATH_TOKEN }}" \
            --type "SecureString" \
            --overwrite
